// Generated by CoffeeScript 1.6.2
(function() {
  var winston;

  winston = require('winston');

  module.exports.logger = new winston.Logger({
    transports: [
      new winston.transports.File({
        filename: 'logs/rpi-ferment-frontend.log'
      })
    ]
  });

}).call(this);
