// Generated by CoffeeScript 1.6.2
(function() {
  var file, http, nodeStatic, path, publicDir, server;

  nodeStatic = require('node-static');

  http = require('http');

  path = require('path');

  publicDir = path.resolve(__dirname + '/../public');

  file = new nodeStatic.Server(publicDir);

  server = http.createServer(function(request, response) {
    request.addListener('end', function() {
      return file.serve(request, response);
    });
    return request.resume();
  });

  server.listen(3030);

}).call(this);
