// Generated by CoffeeScript 1.6.2
(function() {
  var file, http, nodeStatic, server;

  nodeStatic = require('node-static');

  http = require('http');

  file = new nodeStatic.Server('../public');

  server = http.createServer(function(request, response) {
    request.addListener('end', function() {
      return file.serve(request, response);
    });
    return request.resume();
  });

  server.listen(3030);

}).call(this);
