// Generated by CoffeeScript 1.6.2
(function() {
  var app, cluster, i, numCPUs, _i;

  cluster = require('cluster');

  numCPUs = require('os').cpus().length;

  if (cluster.isMaster) {
    for (i = _i = 1; 1 <= numCPUs ? _i <= numCPUs : _i >= numCPUs; i = 1 <= numCPUs ? ++_i : --_i) {
      cluster.fork();
    }
    cluster.on('death', function(worker) {
      console.log('worker ' + worker.pid + ' died');
    });
    return;
  } else {
    app = require('./app');
    app.listen(3020);
    return;
  }

}).call(this);
