// Generated by CoffeeScript 1.6.2
(function() {
  module.exports.routes = function(app) {
    app.get('/', function(req, res) {
      var locals;

      locals = {
        title: 'rpi-ferment dashboard'
      };
      res.render('dashboard.hbs', locals);
    });
  };

}).call(this);
