// Generated by CoffeeScript 1.6.2
(function() {
  var mongoose;

  mongoose = require('mongoose');

  require('../orm/profile.js');

  module.exports.routes = function(app) {
    app.get('/profiles', function(req, res) {
      var findCallback, model;

      model = mongoose.model('Profile');
      findCallback = function(err, profiles) {
        if (!err) {
          return res.send(profiles);
        }
      };
      model.find(findCallback);
    });
    app.post('/profiles', function(req, res) {
      var model, profile, saveCallback;

      model = mongoose.model('Profile');
      profile = new model();
      profile.name = req.body.name;
      profile.control_mode = req.body.control_mode;
      profile.sensor = req.body.sensor;
      profile.steps = req.body.steps;
      profile.active = req.body.active;
      profile.overrides = req.body.overrides;
      saveCallback = function(err) {};
      profile.save(saveCallback);
      return res.send(profile);
    });
    app["delete"]('/profiles/:id', function(req, res) {
      var model;

      model = mongoose.model('Profile');
      console.log('deleting profile ' + req.params.id);
      return model.findByIdAndRemove(req.params.id, function(err, profile) {
        if (!err) {
          return res.send(profile);
        }
      });
    });
    app.put('/profiles/:id', function(req, res) {
      var model;

      model = mongoose.model('Profile');
      return model.findById(req.params.id, function(err, profile) {
        profile.name = req.body.name;
        profile.control_mode = req.body.control_mode;
        profile.sensor = req.body.sensor;
        profile.steps = req.body.steps;
        profile.active = req.body.active;
        profile.overrides = req.body.overrides;
        return profile.save(function(err) {
          if (!err) {
            return res.send(profile);
          }
        });
      });
    });
  };

}).call(this);
